const KEY='seomyeon-member-management-v1';
const dayNames=['월','화','수','목','금','토','일'];
const detailFields=['마음열기(도움)','마음열기(마음수련)','출석·참여','과정 이해','칭찬·격려','잘못된 존재 인식','사진임을 아는가','버려진다는 확신','당위성','메인센터 경험','도반·참도움님과 관계','빼기효과','깨침','감사함'];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{members:[],attendance:{},details:{},weekOffset:0,selectedDetail:null};
let view='weekly';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const pad=n=>String(n).padStart(2,'0');
function monday(d){const x=new Date(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);x.setHours(0,0,0,0);return x}
function currentMonday(){const d=monday(new Date());d.setDate(d.getDate()+state.weekOffset*7);return d}
function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function fmt(d){return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}
function weekDates(){const d=currentMonday();return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x})}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function courseOptions(selected=''){return Array.from({length:9},(_,i)=>`<option value="${i+1}" ${String(selected)===String(i+1)?'selected':''}>${i+1}과정</option>`).join('')}
function attendanceKey(memberId,date){return `${memberId}|${date}`}
function memberAttendance(m){return weekDates().map(d=>state.attendance[attendanceKey(m.id,iso(d))]||'-')}
function lastAttended(m){const entries=Object.entries(state.attendance).filter(([k,v])=>k.startsWith(m.id+'|')&&(v==='○'||v==='상담')).map(([k])=>k.split('|')[1]).sort();return entries.at(-1)||null}
function dormant(m){const last=lastAttended(m);if(!last)return false;const diff=Math.floor((currentMonday()-new Date(last+'T00:00:00'))/86400000);return diff>=28}
function render(){renderTodayDate();renderWeekLabel();renderSummary();renderWeekly();renderMembers();renderDetails()}
function renderTodayDate(){$('#todayDate').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date())}
function renderWeekLabel(){const ds=weekDates();$('#weekLabel').textContent=`${fmt(ds[0])} ~ ${fmt(ds[6])}`}
function renderSummary(){const total=state.members.length;const rows=state.members.map(m=>memberAttendance(m));const attending=rows.filter(a=>a.some(v=>v==='○'||v==='상담')).length;const count=rows.flat().filter(v=>v==='○'||v==='상담').length;const dorm=state.members.filter(dormant).length;$('#totalMembers').textContent=total;$('#attendingMembers').textContent=attending;$('#attendanceCount').textContent=count;$('#dormantMembers').textContent=dorm}
function renderWeekly(){const body=$('#weeklyBody');body.innerHTML='';$('#weeklyEmpty').classList.toggle('hidden',state.members.length>0);for(const m of state.members){const att=memberAttendance(m);const sum=att.filter(v=>v==='○'||v==='상담').length;const detail=state.details[m.id]||{};const tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc(m.name)}</b></td><td>${m.course}과정</td><td>${dormant(m)?'<span class="status-chip dormant">휴면</span>':'<span class="status-chip active">활동</span>'}</td>${att.map((v,i)=>`<td><select class="status-select attendance-select" data-mid="${m.id}" data-date="${iso(weekDates()[i])}">${['-','○','상담','결석'].map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></td>`).join('')}<td class="sum">${sum}</td><td><select class="small-select support-select" data-mid="${m.id}">${['','안정','관찰','도움필요'].map(x=>`<option ${x===(detail.support||'')?'selected':''}>${x||'선택'}</option>`).join('')}</select></td><td><input class="support-input" data-mid="${m.id}" value="${esc(detail.nextSupport||'')}" placeholder="지원 내용"></td>`;body.appendChild(tr)}
$$('.attendance-select').forEach(el=>el.addEventListener('change',e=>{state.attendance[attendanceKey(e.target.dataset.mid,e.target.dataset.date)]=e.target.value;save();renderSummary();renderMembers()}));
$$('.support-select,.support-input').forEach(el=>el.addEventListener('change',e=>{const m=state.details[e.target.dataset.mid]||{};if(e.target.classList.contains('support-select'))m.support=e.target.value==='선택'?'':e.target.value;else m.nextSupport=e.target.value;state.details[e.target.dataset.mid]=m;save()}));}
function renderMembers(){const q=($('#memberSearch')?.value||'').trim();const cf=$('#courseFilter')?.value||'all';const body=$('#membersBody');body.innerHTML='';const list=state.members.filter(m=>(!q||m.name.includes(q))&&(cf==='all'||String(m.course)===cf));$('#membersEmpty').classList.toggle('hidden',list.length>0);for(const m of list){const last=lastAttended(m);const tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc(m.name)}</b></td><td>${m.course}과정</td><td>${last?last:'기록 없음'}</td><td>${dormant(m)?'<span class="status-chip dormant">휴면</span>':'<span class="status-chip active">활동</span>'}</td><td><button class="secondary detail-open" data-mid="${m.id}">상세기록</button></td>`;body.appendChild(tr)}$$('.detail-open').forEach(b=>b.addEventListener('click',()=>{state.selectedDetail=b.dataset.mid;save();switchView('details')}))}
function renderDetails(){const sel=$('#detailMemberSelect');sel.innerHTML=state.members.length?state.members.map(m=>`<option value="${m.id}" ${String(m.id)===String(state.selectedDetail||state.members[0].id)?'selected':''}>${esc(m.name)} · ${m.course}과정</option>`).join(''):'<option>등록된 회원 없음</option>';if(!state.selectedDetail&&state.members[0])state.selectedDetail=state.members[0].id;const m=state.members.find(x=>String(x.id)===String(state.selectedDetail));const panel=$('#detailPanel');if(!m){panel.innerHTML='<div class="empty">회원 등록 후 상세기록을 작성할 수 있습니다.</div>';return}const d=state.details[m.id]||{};panel.innerHTML=`<h3>${esc(m.name)} · ${m.course}과정</h3><p class="muted">매주 관찰한 내용을 상·중·하로 선택하세요. 선택한 값은 자동 저장됩니다.</p><div class="detail-grid">${detailFields.map(f=>`<div class="detail-field"><label>${f}</label><select class="rating" data-field="${esc(f)}" data-mid="${m.id}" data-value="${d[f]||''}"><option value="">선택</option>${['상','중','하'].map(x=>`<option ${d[f]===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</div><div class="detail-field save-note"><label>자유 메모</label><textarea class="note-area" id="detailNote">${esc(d.note||'')}</textarea><button class="primary" id="saveNote">메모 저장</button></div>`;$$('.rating').forEach(el=>{setRatingColor(el);el.addEventListener('change',e=>{const x=state.details[m.id]||{};x[e.target.dataset.field]=e.target.value;state.details[m.id]=x;save();setRatingColor(e.target)})});$('#saveNote').addEventListener('click',()=>{const x=state.details[m.id]||{};x.note=$('#detailNote').value;state.details[m.id]=x;save();$('#saveNote').textContent='저장됨';setTimeout(()=>$('#saveNote').textContent='메모 저장',900)})}
function setRatingColor(el){el.dataset.value=el.value}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function switchView(next){view=next;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(s=>s.classList.toggle('active',s.id===view+'View'));render()}
function openMemberDialog(){const d=$('#memberDialog');$('#memberCourse').innerHTML=courseOptions();$('#memberName').value='';d.showModal()}
$('#prevWeek').addEventListener('click',()=>{state.weekOffset--;save();render()});$('#nextWeek').addEventListener('click',()=>{state.weekOffset++;save();render()});$$('.tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#addMemberBtn').addEventListener('click',openMemberDialog);$('#addMemberFromWeekly').addEventListener('click',openMemberDialog);$('#memberSearch').addEventListener('input',renderMembers);$('#courseFilter').innerHTML+=[...Array(9)].map((_,i)=>`<option value="${i+1}">${i+1}과정</option>`).join('');$('#courseFilter').addEventListener('change',renderMembers);$('#detailMemberSelect').addEventListener('change',e=>{state.selectedDetail=e.target.value;save();renderDetails()});$('#memberForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#memberName').value.trim();if(!name)return;const member={id:crypto.randomUUID(),name,course:$('#memberCourse').value};state.members.push(member);state.selectedDetail=member.id;save();$('#memberDialog').close();render()});
render();
